### PR TITLE
Update/#224 getting started page update

### PR DESCRIPTION
**Pull request by daniel-cy-lu**
Getting started page responsive css completed. The url of this page is ("root/documentation")

Figma link to the mock up: https://www.figma.com/file/fXh58MfxEDh1ssgxQyPb5f/Overture_Refresh?type=design&node-id=1167-8959&mode=design&t=4QYifUPLUphipp6O-0

### CODE REVIEW

**Comment by MitchellShiell** [comment]
User docs should link to the respective intro pages (overture.bio documentation) of each component.

Developer docs, should direct to the GitHub wiki for that component: https://github.com/overture-stack/SONG/wiki
- I will have these updated before launch, at the very least with an under-construction message in the wiki

**Comment by MitchellShiell** [comment]
Maybe for a different PR, but the documentation Overview link in the navBar should be more visible, 

Currently: 

Screenshot 2023-09-07 at 11 06 22 AM

Mock up:

Screenshot 2023-09-07 at 11 07 39 AM

**Comment by ciaranschutte** [comment]
code looks ok.
@daniel-cy-lu  let's update https://github.com/overture-stack/website/pull/309#issuecomment-1709183608 then we can merge

**Comment by daniel-cy-lu** [comment]
> Maybe for a different PR, but the documentation Overview link in the navBar should be more visible,
> 
> Currently:
> 
> Screenshot 2023-09-07 at 11 06 22 AM
> Mock up:
> 
> Screenshot 2023-09-07 at 11 07 39 AM

The link is red and has an arrow to its right now

**Comment by daniel-cy-lu** [comment]
> User docs should link to the respective intro pages (overture.bio documentation) of each component.
> 
> Developer docs, should direct to the GitHub wiki for that component: https://github.com/overture-stack/SONG/wiki
> 
> * I will have these updated before launch, at the very least with an under-construction message in the wiki

The links are working now.

**Review by ciaranschutte — APPROVED** [review]

**Pull request merged**
