### PR TITLE
Docs - header & footer

### PR DESCRIPTION
**Pull request by samrichca**

### CODE REVIEW

**Review by anncatton — COMMENTED** [review]
I see a lot of changes that just add/remove trailing slashes for urls. Can we maybe take advantage of something like `url-join` to ensure these urls are constructed correctly?

**Comment by samrichca** [comment]
@anncatton good suggestion, i looked into that but it doesn't allow/handle trailing slashes. i'm thinking about making a utility for normalizing URLs (probably including url-join but then doing workarounds to preserve trailing slashes)... and a reusable component for links (in order to handle links in markdown, which could be local or external, and have to use a different element/component depending on that) that will use the URL utility. i may need to use it on the whole site, so it should be its own ticket.

**Comment by samrichca** [comment]
hmmm there's also this option https://openbase.io/js/proper-url-join/documentation

**Comment by anncatton** [comment]
> @anncatton good suggestion, i looked into that but it doesn't allow/handle trailing slashes. i'm thinking about making a utility for normalizing URLs (probably including url-join but then doing workarounds to preserve trailing slashes)... and a reusable component for links (in order to handle links in markdown, which could be local or external, and have to use a different element/component depending on that) that will use the URL utility. i may need to use it on the whole site, so it should be its own ticket.
> 
> i found this which would work a lot better https://openbase.io/js/proper-url-join/documentation

cool, sounds like a plan. maybe create a ticket now and then we won't forget :)

**Review by anncatton — APPROVED** [review]

**Pull request merged**
