### PR TITLE
Rc/1.4.0

### PR DESCRIPTION
**Pull request by samrichca**
- add Score docs

### CODE REVIEW

**Review by b-f-chan — APPROVED** [review]
Thanks @samrichca, the changes are exactly the ones I have incorporated.  I approved, but is it possible to see the netlify version?  Or do we have to do the merge into master first before we can netlify?

**Comment by b-f-chan** [comment]
@jaserud if you can have a quick review as well before @samrichca merges this into master.  The changes are exactly what I have added previously, so just a quick sanity check.  Sam will generate a final netlify after merging to master before we publish to prod.  Thanks!

**Review by jaserud — APPROVED** [review]
LGTM

**Comment by samrichca** [comment]
> @jaserud if you can have a quick review as well before @samrichca merges this into master. The changes are exactly what I have added previously, so just a quick sanity check. Sam will generate a final netlify after merging to master before we publish to prod. Thanks!

just to clarify, merging to master initiates the prod deployment automatically on netlify's side

i'll post the netlify link on slack before merging

**Pull request merged**
