### PR TITLE
Feat/#174 upgrades

### PR DESCRIPTION
**Pull request by ciaranschutte**
- major versions upgrades for gatsby and associated plugins
- adds npm overrides (gatsby recommends Yarn but we are using npm)
- adds and configs `transformer-remark` to display images

### CODE REVIEW

**Review by mistryrn — APPROVED** [review]
🚀

**Comment by caravinci** [comment]
Not a Gatsby expert, so I won't even venture reviewing the changes lol, though they all look reasonable...
however, I think the "overrides" requires NPM version enforcement, like we did in DMS-UI, @ciaranschutte

**Comment by ciaranschutte** [comment]
> Not a Gatsby expert, so I won't even venture reviewing the changes lol, though they all look reasonable... however, I think the "overrides" requires NPM version enforcement, like we did in DMS-UI, @ciaranschutte

yes ! good shout I was forgetting that thank you

**Comment by samrichca** [comment]
looks good and builds without errors 💯  🚀

**Pull request merged**
